### ISSUE TITLE
How can I target the Picker text alignment on Android?

### ISSUE THREAD

**Issue by GollyJer** [GeekyAnts/NativeBase#1716]
Hi. I'd like to `justifyContent: 'flex-end'` for the text inside a picker but it seems to have no affect on Android.

I'm trying to move `3 hours` and `Yes` right justified next to the dropdown.

Thanks for any help!
![screenshot_20180322-093357](https://user-images.githubusercontent.com/689204/37773812-eedfd350-2db4-11e8-9c6c-6361c003e51e.png)

**Comment by SupriyaKalghatgi** [comment]
@GollyJer Take a look at NativeBase-KitchenSink for examples
https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/src/screens/list/list-icon.js

**Comment by SupriyaKalghatgi** [comment]
@stokesbga I shared source code of similar use case
I am sorry if you cant do this either

**Comment by stokesbga** [comment]
The use case is to put the picker in `<Right></Right>`? That didnt work for me

**Comment by GollyJer** [comment]
@stokesbga Yeah, the answer here wasn't helpful but we figured it out on our own.

Here's the component code from the screenshot above.
```html
<View style={rowContainer}>
  <Text style={rowLabelText}>Timeline Interval</Text>
  <Picker
    style={internalPickerContainer}
    mode="dropdown"
    iosHeader="Select Interval"
    selectedValue={timeInterval}
    onValueChange={setTimeInterval}
    //
    itemStyle={pickerIosListItemContainer}
    itemTextStyle={pickerIosListItemText}
  >
    <Picker.Item label="1 hour" value={1} />
    <Picker.Item label="2 hours" value={2} />
    <Picker.Item label="3 hours" value={3} />
  </Picker>
</View>
```

To start, the row with the title and the picker needs to be `space-between` justified to push the title to the left and the picker to the right.
```css
  rowContainer: {
    height: 64,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: 16,
  },
```

Then, to "align" the text to the right you actually have to resize the picker on Android.
```css
  internalPickerContainer: {
    flex: Platform.OS === 'ios' ? 1 : null, // for Android, not visible otherwise.
    width: Platform.OS === 'ios' ? undefined : 120,
  },
```

And for completion... here's the remaining css.
```css
  pickerIosListItemContainer: {
    flex: 1,
    height: 60,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pickerIosListItemText: {
    fontSize: 16,
  },
  ```

Hopefully that helps.
