### ISSUE TITLE
Cannot override `Button` component theme `_text` color in `_dark` property

### ISSUE THREAD

**Issue by Swiftwork** [GeekyAnts/NativeBase#5436]
### Description

Extending theme should override defaults.

### CodeSandbox/Snack link

https://snack.expo.dev/@swiftwork/button-theme-override

### Steps to reproduce

Extend the `Button` theme with an identical definition to the [default component theme](https://github.com/GeekyAnts/NativeBase/blob/v3.4.15/src/theme/components/button.ts#L112-L114)
```css
_dark: {
  _text: {
    color: '#00f'
  }
}
```
wont work, but switching order will
```css
_text: {
  _dark: {
    color: '#00f'
  }
}
```

### NativeBase Version

3.4.15

### Platform

- [X] Android
- [X] CRA
- [X] Expo
- [X] iOS
- [X] Next

### Additional Information

Discord discussion https://discord.com/channels/785491682719301643/1025200721072763042/1025396759041687662
